### ISSUE TITLE
Construct Driver Station

### ISSUE THREAD

**Issue by davidcalderon03** [RoboJackets/urc-rover#118]
This will be needed for teleoperation of the rover. Assignee should review the contents of urc_teleop and integrate any necessary components (particularly, rosbridge integration), and develop a web interface that communicates over the ROS2 network. Some basic functionality will include choosing waypoints, seeing arm inverse kinematics in action, and seeing relevant status updates of the rover.

**Comment by abhiramg2021** [comment]
https://docs.google.com/document/d/1gCkEF6uA3NSc5FNXcKRdVGkY6JcKDr5DNHmobeHjQuo/edit
